// Render ideas to Markdown format

import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';
import { getConfig } from '../config/loadConfig.js';
import { log } from '../utils/log.js';
import { slugify } from '../utils/text.js';
import { getIdeas, getStats } from '../store/db.js';
import type { Idea } from '../store/models.js';

/**
 * Render TOP_20_IDEAS.md
 */
export function renderTopIdeasMarkdown(): string {
  const ideas = getIdeas();
  const stats = getStats();

  const lines: string[] = [];

  // Header
  lines.push('# Reddit Idea Miner - Top 20 SaaS Ideas');
  lines.push('');
  lines.push(`Generated: ${new Date().toISOString()}`);
  lines.push('');

  // Executive Summary
  lines.push('## Executive Summary');
  lines.push('');
  lines.push(`This report presents the top ${ideas.length} SaaS product ideas discovered through automated analysis of Reddit discussions.`);
  lines.push('');
  lines.push('### Data Coverage');
  lines.push('');
  lines.push(`- **Subreddits Tracked**: ${stats.subreddits}`);
  lines.push(`- **Posts Analyzed**: ${stats.posts}`);
  lines.push(`- **Comments Processed**: ${stats.comments}`);
  lines.push(`- **Threads with Full Analysis**: ${stats.threadsAnalyzed}`);
  lines.push(`- **Insights Extracted**: ${stats.insights}`);
  lines.push(`- **Clusters Formed**: ${stats.clusters}`);
  lines.push('');

  // Scoring explanation
  lines.push('### Scoring Methodology');
  lines.push('');
  lines.push('Each idea is scored on four dimensions (0-10 scale):');
  lines.push('');
  lines.push('- **Pain Score**: Intensity and frequency of pain point mentions');
  lines.push('- **Intent Score**: Evidence of buying intent and solution-seeking');
  lines.push('- **Frequency Score**: How often this problem appears across threads');
  lines.push('- **Buildability Score**: Technical feasibility as an MVP');
  lines.push('');
  lines.push('Total Score = (Pain × 0.25) + (Intent × 0.25) + (Frequency × 0.25) + (Buildability × 0.15) + (Cross-sub × 0.10)');
  lines.push('');

  // Ideas
  lines.push('---');
  lines.push('');
  lines.push('## Top Ideas');
  lines.push('');

  for (const idea of ideas) {
    lines.push(`### #${idea.rank}. ${idea.name}`);
    lines.push('');
    lines.push(`> ${idea.one_liner}`);
    lines.push('');
    lines.push(`**Target Persona**: ${idea.target_persona}`);
    lines.push('');

    // Scores
    lines.push('**Scores**:');
    lines.push(`| Pain | Intent | Frequency | Buildability | **Total** |`);
    lines.push(`|------|--------|-----------|--------------|-----------|`);
    lines.push(`| ${idea.scores.pain.toFixed(1)} | ${idea.scores.intent.toFixed(1)} | ${idea.scores.frequency.toFixed(1)} | ${idea.scores.buildability.toFixed(1)} | **${idea.scores.total.toFixed(1)}** |`);
    lines.push('');

    // MVP Workflow
    lines.push('**MVP Workflow**:');
    lines.push('');
    for (let i = 0; i < idea.mvp_workflow.length; i++) {
      lines.push(`${i + 1}. ${idea.mvp_workflow[i]}`);
    }
    lines.push('');

    // MVP Features
    lines.push('**Must-Have Features**:');
    lines.push('');
    for (const feature of idea.mvp_features) {
      lines.push(`- ${feature}`);
    }
    lines.push('');

    // Pricing
    lines.push(`**Pricing Hypothesis**: ${idea.pricing_hypothesis}`);
    lines.push('');

    // Why it wins
    lines.push(`**Why It Wins**: ${idea.why_it_wins}`);
    lines.push('');

    // Evidence
    lines.push('**Evidence**:');
    lines.push('');
    for (const url of idea.evidence_urls.slice(0, 3)) {
      lines.push(`- [Thread](${url})`);
    }
    lines.push('');
    lines.push(`📄 [Full evidence pack](./EVIDENCE/${slugify(idea.name)}.md)`);
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  // Footer
  lines.push('');
  lines.push('## Methodology Notes');
  lines.push('');
  lines.push('This report was generated using the Reddit Idea Miner system:');
  lines.push('');
  lines.push('1. **Discovery**: 500+ high-intent subreddits identified through market mapping');
  lines.push('2. **Ingestion**: Posts and comments fetched via Reddit JSON API');
  lines.push('3. **Signal Extraction**: Heuristic scoring for pain language and buying intent');
  lines.push('4. **LLM Analysis**: Structured insight extraction using GPT-4o-mini');
  lines.push('5. **Clustering**: K-means clustering on embedded pain points');
  lines.push('6. **Idea Generation**: LLM synthesis of product concepts from clusters');
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('*Generated by Reddit Idea Miner*');

  return lines.join('\n');
}

/**
 * Render evidence pack for a single idea
 */
export function renderEvidenceMarkdown(idea: Idea): string {
  const lines: string[] = [];

  lines.push(`# Evidence Pack: ${idea.name}`);
  lines.push('');
  lines.push(`> ${idea.one_liner}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // Source threads
  lines.push('## Source Threads');
  lines.push('');
  for (let i = 0; i < idea.evidence_urls.length; i++) {
    lines.push(`${i + 1}. ${idea.evidence_urls[i]}`);
  }
  lines.push('');

  // Evidence snippets
  lines.push('## Evidence Snippets');
  lines.push('');
  for (let i = 0; i < idea.evidence_snippets.length; i++) {
    const snippet = idea.evidence_snippets[i]!;
    lines.push(`### Snippet ${i + 1}`);
    lines.push('');
    lines.push(`**Source**: [Thread](${snippet.thread_url}) (Comment: ${snippet.comment_id})`);
    lines.push('');
    lines.push('```');
    lines.push(snippet.text);
    lines.push('```');
    lines.push('');
  }

  // Scores
  lines.push('## Scoring Details');
  lines.push('');
  lines.push(`- Pain Score: ${idea.scores.pain.toFixed(1)}/10`);
  lines.push(`- Intent Score: ${idea.scores.intent.toFixed(1)}/10`);
  lines.push(`- Frequency Score: ${idea.scores.frequency.toFixed(1)}/10`);
  lines.push(`- Buildability Score: ${idea.scores.buildability.toFixed(1)}/10`);
  lines.push(`- **Total Score: ${idea.scores.total.toFixed(1)}**`);
  lines.push('');

  lines.push('---');
  lines.push('');
  lines.push(`*Evidence pack for idea #${idea.rank}*`);

  return lines.join('\n');
}

/**
 * Write all reports to deliverables directory
 */
export function writeReports(): void {
  const config = getConfig();
  const deliverablesDir = config.paths.deliverables;
  const evidenceDir = join(deliverablesDir, 'EVIDENCE');

  // Ensure directories exist
  if (!existsSync(evidenceDir)) {
    mkdirSync(evidenceDir, { recursive: true });
  }

  const ideas = getIdeas();

  // Write TOP_20_IDEAS.md
  const topIdeasMd = renderTopIdeasMarkdown();
  const topIdeasPath = join(deliverablesDir, 'TOP_20_IDEAS.md');
  writeFileSync(topIdeasPath, topIdeasMd);
  log.info('REPORT', `Wrote ${topIdeasPath}`);

  // Write evidence packs
  for (const idea of ideas) {
    const evidenceMd = renderEvidenceMarkdown(idea);
    const evidencePath = join(evidenceDir, `${slugify(idea.name)}.md`);
    writeFileSync(evidencePath, evidenceMd);
    log.debug('REPORT', `Wrote ${evidencePath}`);
  }

  log.info('REPORT', `Wrote ${ideas.length} evidence packs`);
}

export default {
  renderTopIdeasMarkdown,
  renderEvidenceMarkdown,
  writeReports,
};
